### ISSUE TITLE
Tells me i  reached my current quota (and to check my billing and plan details), first time using it

### ISSUE THREAD

**Issue by azenia** [RIvance/minecraft-chatgpt-assistant#4]
Basically title, i generated an API key from openAI, inserted it.
Or does this require you to pay for chatGPT premium? 

![image](https://user-images.githubusercontent.com/77856893/232135866-2341643b-47d1-4237-9c17-551f52a9da56.png)

**Comment by RIvance** [comment]
This may help:
https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

**Comment by azenia** [comment]
Ah okay it requires a paid plan, i thought you could have a set amount of requests before that. Thanks

**Comment by RIvance** [comment]
Did you get your $5 free experimenting credits? If no, maybe you can try to contact them at [support@openai.com](mailto:support@openai.com). There's no need for a paid plan before you run out of your free credits.

**Comment by azenia** [comment]
I've sent them a mail, thanks
