### ISSUE TITLE
error command.. It looks like gpt added another slash. like //gamemode 1

### ISSUE THREAD

**Issue by mocxlbor** [RIvance/minecraft-chatgpt-assistant#6]
error command.. It looks like gpt added another slash. like //gamemode 1error command.. It looks like gpt added another slash. like //gamemode 1
![image](https://user-images.githubusercontent.com/121931214/232377484-e303e528-0108-473a-af54-09faf76e7c4a.png)

**Comment by mocxlbor** [comment]
![image](https://user-images.githubusercontent.com/121931214/232377534-18b0af89-168b-4693-a62d-7bfe1bc65c1b.png)

**Comment by RIvance** [comment]
Thanks for the feedback. It will be fixed in the next version.

**Comment by RIvance** [comment]
Fixed in [v1.0.3](https://github.com/RIvance/minecraft-chatgpt-assistant/releases/tag/1.0.3).
